package modul10;


import javax.swing.JOptionPane;
import modul10.setor;
import modul10.tarik;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Puspita
 */
public class pilihTransaksi extends javax.swing.JFrame {
    String str, str1;
    int choice,z,pin=1234,counter=0,a=3;
    int t,s,tab=500000;

    /**
     * Creates new form pilihTransaksi
     */
    public pilihTransaksi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        buttonKeluar = new javax.swing.JButton();
        buttonSaldo = new javax.swing.JButton();
        buttonSetor = new javax.swing.JButton();
        buttonTarik = new javax.swing.JButton();
        buttonPetunjuk = new javax.swing.JButton();

        jButton8.setText("jButton8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pilih Transaksi");
        setBackground(new java.awt.Color(0, 0, 204));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel1.setText("KELUAR");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(300, 160, 80, 30);

        jLabel2.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel2.setText("INFORMASI SALDO");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 50, 130, 30);

        jLabel3.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel3.setText("PENYETORAN");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 120, 100, 30);

        jLabel4.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel4.setText("PENARIKAN");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 190, 90, 30);

        jLabel5.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel5.setText("PETUNJUK");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(290, 80, 80, 30);

        buttonKeluar.setText("5");
        buttonKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonKeluar);
        buttonKeluar.setBounds(370, 160, 50, 30);

        buttonSaldo.setText("1");
        buttonSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaldoActionPerformed(evt);
            }
        });
        getContentPane().add(buttonSaldo);
        buttonSaldo.setBounds(10, 50, 50, 30);

        buttonSetor.setText("2");
        buttonSetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSetorActionPerformed(evt);
            }
        });
        getContentPane().add(buttonSetor);
        buttonSetor.setBounds(10, 120, 50, 30);

        buttonTarik.setText("3");
        buttonTarik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTarikActionPerformed(evt);
            }
        });
        getContentPane().add(buttonTarik);
        buttonTarik.setBounds(10, 190, 50, 30);

        buttonPetunjuk.setText("4");
        buttonPetunjuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPetunjukActionPerformed(evt);
            }
        });
        getContentPane().add(buttonPetunjuk);
        buttonPetunjuk.setBounds(370, 80, 50, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaldoActionPerformed
        // TODO add your handling code here:
       this.setVisible(false);
       JOptionPane.showMessageDialog(null,"Saldo Anda saat ini sebesar : "+tab);
       z=JOptionPane.showConfirmDialog(null, "Melanjutkan transaksi lain ?","ATM BNI SYARIAH-BOJONEGORO",JOptionPane.YES_NO_OPTION, 3);
       if (z==0){
           this.setVisible(true);
       }
       else{
           JOptionPane.showMessageDialog(null, "Terimakasih telah menggunakan ATM BNI SYARIAH-BOJONEGORO, ambil kartu ATM Anda");
           System.exit(0);
       }
    }//GEN-LAST:event_buttonSaldoActionPerformed

    private void buttonTarikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTarikActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
       str1 = JOptionPane.showInputDialog(null,"Masukkan jumlah penarikan: ");
       t = Integer.parseInt(str1);
       tarik mengambil = new tarik();
       mengambil.ambil(tab, t);
       tab = mengambil.getsaldo();
       
       z=JOptionPane.showConfirmDialog(null, "Melanjutkan transaksi lain ?","ATM BNI SYARIAH-BOJONEGORO",JOptionPane.YES_NO_OPTION, 3);
       if (z==0){
           this.setVisible(true);
       }
       else{
           JOptionPane.showMessageDialog(null, "Terimakasih telah menggunakan ATM BNI SYARIAH-BOJONEGORO, ambil kartu ATM Anda");
           System.exit(0);
       }
    }//GEN-LAST:event_buttonTarikActionPerformed

    private void buttonSetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSetorActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
       str1 = JOptionPane.showInputDialog(null,"Masukkan jumlah penyetoran: ");
       s = Integer.parseInt(str1);
       setor hasil = new setor();
       hasil.menabung(tab, s);
       tab = hasil.getsaldo();
       
       z=JOptionPane.showConfirmDialog(null, "Melanjutkan transaksi lain ?","ATM BNI SYARIAH-BOJONEGORO",JOptionPane.YES_NO_OPTION, 3);
       if (z==0){
           this.setVisible(true);
       }
       else{
           JOptionPane.showMessageDialog(null, "Terimakasih telah menggunakan ATM BNI SYARIAH-BOJONEGORO, ambil kartu ATM Anda");
           System.exit(0);
       }
    }//GEN-LAST:event_buttonSetorActionPerformed

    private void buttonPetunjukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPetunjukActionPerformed
        // TODO add your handling code here:aksi lain ?","ATM BNI SYARIAH-BOJONEGORO",JOptionPane.YES_NO_OPTION, 3
        z=JOptionPane.showConfirmDialog(null, "Cara penggunaan Aplikasi\n [1] Masukkan PIN dengan benar\n[2]Bertransaksilah dengan benar sesuai pilihan\n[3]Gunakan uang sesuai kebutuhan dan rajinlah menabung\n","INFO",JOptionPane.YES_NO_OPTION, 3);

       if (z==0){
           this.setVisible(true);
       }
       else{
           JOptionPane.showMessageDialog(null, "Terimakasih telah menggunakan ATM BNI SYARIAH-BOJONEGORO, ambil kartu ATM Anda");
           System.exit(0);
       }
    }//GEN-LAST:event_buttonPetunjukActionPerformed

    private void buttonKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKeluarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"SILAHKAN AMBIL KARTU ATM ANDA !","TERIMAKASIH",JOptionPane.WARNING_MESSAGE);
        System.exit(0);
    }//GEN-LAST:event_buttonKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pilihTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pilihTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pilihTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pilihTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pilihTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonKeluar;
    private javax.swing.JButton buttonPetunjuk;
    private javax.swing.JButton buttonSaldo;
    private javax.swing.JButton buttonSetor;
    private javax.swing.JButton buttonTarik;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
